emmental:
  lr: 2e-5
  n_steps: 50
  steps_learned: 20
  evaluation_freq: 10
  checkpoint_freq: 1
  counter_unit: batch
  checkpoint_all: true
  clear_intermediate_checkpoints: false
  lr_scheduler: linear
  grad_clip: 1.0
  l2: 0.01
  log_path: logs/turtorial
  device: 0
  model_path: logs/turtorial/2021_09_03/14_09_34/aecbc69a/checkpoint_20.model.pth
  skip_learned_data: True
run_config:
  eval_batch_size: 16
  dataloader_threads: 0
  dataset_threads: 2
  log_level: info
train_config:
  batch_size: 2
model_config:
  hidden_size: 64
data_config:
  data_dir: data/sample_text_data
  data_prep_dir: prep
  entity_dir: data/sample_entity_data
  overwrite_preprocessed_data: false
  use_entity_desc: false
  entity_type_data:
    use_entity_types: true
    type_symbols_dir: type_mappings/wiki
  entity_kg_data:
    use_entity_kg: true
    kg_labels: kg_mappings/qid2relations.json
    kg_vocab: kg_mappings/relation_vocab.json
  max_seq_len: 64
  max_seq_window_len: 32
  max_ent_len: 64
  dev_dataset:
    file: dev.jsonl
    use_weak_label: true
  test_dataset:
    file: dev.jsonl
    use_weak_label: true
  train_dataset:
    file: train.jsonl
    use_weak_label: true
  train_in_candidates: true
  word_embedding:
    cache_dir: data/pretrained_bert_models
    context_layers: 1
    entity_layers: 1
