emmental:
  lr: 2e-5
  n_epochs: 5
  evaluation_freq: 1.0
  warmup_percentage: 0.1
  lr_scheduler: linear
  log_path: logs_medmentions_0203/cls_bio
  checkpointing: true
  checkpoint_all: true
  checkpoint_freq: 1
  online_eval: false
  clear_intermediate_checkpoints: false
  checkpoint_metric: NED/Bootleg/dev/final_loss/acc_boot:max
  l2: 0.01
  grad_clip: 1.0
  gradient_accumulation_steps: 4
  fp16: false
run_config:
  eval_batch_size: 64
  dataloader_threads: 1
  dataset_threads: 50
  spawn_method: fork
train_config:
  batch_size: 16
model_config:
  hidden_size: 512
  num_heads: 16
  num_model_stages: 1
  ff_inner_size: 1024
  attn_class: BootlegMed
data_config:
  data_dir: /dfs/scratch0/lorr1/projects/bootleg-data/data/medmentions_0203/spacy_10_exp_noNC
  data_prep_dir: prep
  emb_dir: /dfs/scratch0/lorr1/projects/bootleg-data/data/medmentions_0203/spacy_10_exp_noNC/embs
  eval_slices:
    - unif_TS
    - unif_NS_TS
    - unif_TO
    - unif_NS_TO
    - unif_TL
    - unif_NS_TL
  type_prediction:
    use_type_pred: false
    num_types: 21
    file: qid2types.json
  ent_embeddings:
#       - key: learned
#         load_class: LearnedEntityEmb
#         freeze: false
#         cpu: true
#         args:
#           learned_embedding_size: 256
#           regularize_mapping: /dfs/scratch0/lorr1/projects/bootleg-data/data/medmentions_0203/spacy_10_exp_noNC/qid2reg_pow.csv
       - key: title
         load_class: TitleEmbCLS
         freeze: false # Freeze the projection layer or not
         send_through_bert: true
         args:
           requires_grad: true
           proj: 256
       - key: learned_type
         load_class: LearnedTypeEmb
         freeze: false
         args:
           type_labels: qid2types.json
           max_types: 5
           type_dim: 128
           merge_func: addattn
           attn_hidden_size: 128
#       - key: learned_type_relations
#         load_class: LearnedTypeEmb
#         freeze: false
#         args:
#           type_labels: kg_relation_types_1229.json
#           max_types: 50
#           type_dim: 128
#           merge_func: addattn
#           attn_hidden_size: 128
#       - key: adj_index
#         load_class: KGIndices
#         batch_on_the_fly: true
#         normalize: false
#         args:
#           kg_adj: kg_adj_1229.txt
  entity_dir: /dfs/scratch0/lorr1/projects/bootleg-data/data/medmentions_0203/spacy_10_exp_noNC/entity_db
  max_aliases: 1
  max_seq_len: 100
  overwrite_preprocessed_data: false
  dev_dataset:
    file: dev.jsonl
    use_weak_label: true
  test_dataset:
    file: dev.jsonl
    use_weak_label: true
  train_dataset:
    file: train.jsonl
    use_weak_label: true
  train_in_candidates: true
  word_embedding:
    cache_dir: /dfs/scratch0/lorr1/projects/bootleg-data/embs/pretrained_bert_models
    freeze: false
    layers: 4
    bert_model: microsoft/BiomedNLP-PubMedBERT-base-uncased-abstract
